import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Share2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { Pill } from "../components/ui";
import { getTripById, subscribeToTrips } from "../services/tripStore";
import { activityDate, formatTripDate, getTripDays, totalActivityCost, tripDurationDays } from "../services/tripUtils";
import { Trip } from "../types";

export function Itinerary() {
  const { id } = useParams();
  const [trip, setTrip] = useState<Trip | undefined>(() => (id ? getTripById(id) : undefined));
  useEffect(() => subscribeToTrips(() => setTrip(id ? getTripById(id) : undefined)), [id]);

  const days = useMemo(() => trip ? getTripDays(trip) : [], [trip]);
  if (!trip) return <div className="panel p-8 text-center"><h1 className="font-display text-2xl font-bold">Trip not found</h1><Link to="/trips" className="btn-primary mt-5 inline-flex">Back to My Trips</Link></div>;

  return <div className="mx-auto max-w-5xl space-y-7"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-black/45"><ArrowLeft size={16}/> Back</Link><div className="relative overflow-hidden rounded-[30px]"><img src={trip.cover} alt={trip.name} className="h-[360px] w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute bottom-7 left-6 right-6 text-white sm:left-9"><Pill tone="green">{tripDurationDays(trip)} days · {trip.cities.length} {trip.cities.length === 1 ? "city" : "cities"}</Pill><h1 className="mt-3 font-display text-4xl font-extrabold">{trip.name}</h1><p className="mt-2 text-white/75">{trip.cities.map(city => city.name).join(" → ")} · {formatTripDate(trip.start, false)}–{formatTripDate(trip.end, false)}</p></div></div><div className="grid gap-4 sm:grid-cols-3"><div className="panel p-5"><span className="text-xs text-black/40">Duration</span><b className="mt-1 block text-xl">{tripDurationDays(trip)} days</b></div><div className="panel p-5"><span className="text-xs text-black/40">Cities</span><b className="mt-1 block text-xl">{trip.cities.length}</b></div><div className="panel p-5"><span className="text-xs text-black/40">Planned cost</span><b className="mt-1 block text-xl">₹{totalActivityCost(trip.activities).toLocaleString("en-IN")}</b></div></div><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-display text-2xl font-bold">Trip overview</h2><div className="flex gap-2"><Link to={`/trips/${trip.id}/calendar`} className="btn-secondary">Calendar</Link><Link to={`/trips/${trip.id}/builder`} className="btn-secondary">Edit itinerary</Link><button type="button" className="btn-primary"><Share2 size={16}/> Share trip</button></div></div><div className="space-y-5">{days.map((day, index) => { const activities = trip.activities.filter(activity => activityDate(activity, trip) === day); return <div className="panel p-5 sm:p-6" key={day}><div className="flex items-center gap-3"><Pill tone="green">DAY {index + 1}</Pill><span className="text-sm font-semibold text-black/45">{formatTripDate(day)}</span></div><h3 className="mt-3 font-display text-xl font-bold">{trip.cities[Math.min(trip.cities.length - 1, Math.floor(index / Math.max(1, Math.ceil(days.length / trip.cities.length))))]?.name || "Trip day"}</h3>{activities.length ? <div className="mt-4 space-y-2">{activities.map(activity => <div key={activity.id} className="flex items-center justify-between gap-4 rounded-xl bg-black/[.03] p-3"><div><p className="text-sm font-semibold">{activity.time} · {activity.name}</p><p className="text-xs text-black/45">{activity.category} · {activity.duration}</p></div><b className="text-sm">₹{activity.cost.toLocaleString("en-IN")}</b></div>)}</div> : <p className="mt-1 text-sm text-black/45">No activities planned yet.</p>}</div>; })}</div></div>;
}
