import { useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ArrowLeft, ArrowRight, Check, MapPin } from "lucide-react";
import { cities } from "../data/mock";
import { saveCreatedTrip } from "../services/tripStore";
import { Trip } from "../types";

const today = new Date().toISOString().slice(0,10);
const formatDate = (value:string) => new Date(`${value}T12:00:00`).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"});
const slugify = (value:string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"") || "new-trip";

export function NewTrip(){
 const navigate=useNavigate(); const [step,setStep]=useState(1); const [name,setName]=useState("My next adventure"); const [budget,setBudget]=useState("80000"); const [startDate,setStartDate]=useState(today); const [endDate,setEndDate]=useState(""); const [selectedCityIds,setSelectedCityIds]=useState<string[]>(["paris","amsterdam","berlin"]);
 const selectedCities=useMemo(()=>cities.filter(c=>selectedCityIds.includes(c.id)),[selectedCityIds]);
 const toggleCity=(id:string)=>setSelectedCityIds(cur=>cur.includes(id)?cur.filter(x=>x!==id):[...cur,id]);
 const next=()=>{ if(step<4){setStep(s=>s+1);return;} const trip:Trip={id:`${slugify(name)}-${Date.now()}`,name:name.trim()||"My next adventure",start:startDate,end:endDate||startDate,budget:Math.max(0,Number(budget)||0),cover:selectedCities[0]?.image||cities[0].image,cities:selectedCities.length?selectedCities:[cities[0]],activities:[]}; saveCreatedTrip(trip); navigate(`/trips/${trip.id}/builder`);};
 return <div className="mx-auto max-w-4xl space-y-7 pb-8"><button type="button" onClick={()=>navigate("/dashboard")} className="inline-flex items-center gap-2 text-sm font-semibold text-black/50 hover:text-ink"><ArrowLeft size={16}/> Back to dashboard</button><div><div className="eyebrow">Create a trip</div><h1 className="mt-2 font-display text-4xl font-extrabold">Let’s map out your next story.</h1></div><div className="panel p-5 sm:p-8"><div className="mb-8 flex items-center justify-between gap-2">{["Basics","Destinations","Budget","Review"].map((label,i)=>{const n=i+1;return <div key={label} className="flex flex-1 items-center gap-2"><div className={`grid h-9 w-9 shrink-0 place-items-center rounded-full text-sm font-bold ${n<=step?"bg-mint text-white":"bg-black/5 text-black/35"}`}>{n<step?<Check size={16}/>:n}</div><span className={`hidden text-xs font-bold sm:block ${n<=step?"text-ink":"text-black/35"}`}>{label}</span>{n<4&&<div className={`h-px flex-1 ${n<step?"bg-mint":"bg-black/10"}`}/>}</div>})}</div>
 {step===1&&<div className="grid gap-5"><div><label className="mb-2 block text-sm font-bold">Trip name</label><input className="input" value={name} onChange={e=>setName(e.target.value)}/></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="mb-2 block text-sm font-bold">Start date</label><input className="input" type="date" value={startDate} onChange={e=>{setStartDate(e.target.value);if(endDate&&e.target.value>endDate)setEndDate(e.target.value)}} min={today}/></div><div><label className="mb-2 block text-sm font-bold">End date</label><input className="input" type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} min={startDate}/></div></div></div>}
 {step===2&&<div><p className="mb-4 text-sm text-black/50">Pick the cities you want to include.</p><div className="grid gap-3 sm:grid-cols-2">{cities.map(c=>{const selected=selectedCityIds.includes(c.id);return <button key={c.id} type="button" onClick={()=>toggleCity(c.id)} aria-pressed={selected} className={`flex items-center gap-3 rounded-2xl border p-3 text-left transition ${selected?"border-mint bg-mint/5":"border-black/10 hover:border-mint/50"}`}><img src={c.image} alt={c.name} className="h-16 w-20 rounded-xl object-cover"/><div><b>{c.name}</b><p className="text-xs text-black/45">{c.country} · {c.costIndex}</p></div><MapPin className={`ml-auto ${selected?"text-mint":"text-black/20"}`} size={17}/></button>})}</div><p className="mt-3 text-xs font-semibold text-black/40">{selectedCities.length} {selectedCities.length===1?"city":"cities"} selected</p></div>}
 {step===3&&<div className="mx-auto max-w-xl"><label className="mb-2 block text-sm font-bold">Trip budget</label><div className="relative"><span className="absolute left-4 top-3 text-black/40">₹</span><input className="input pl-8 text-lg font-bold" min="0" type="number" value={budget} onChange={e=>setBudget(e.target.value)}/></div><div className="mt-5 rounded-2xl bg-[#eef6f2] p-5"><div className="text-xs font-bold text-mint">Planning target</div><p className="mt-1 text-sm text-black/60">Your new trip will appear on the dashboard immediately after creation.</p></div></div>}
 {step===4&&<div className="rounded-2xl bg-black/[.03] p-6"><div className="text-xs font-bold text-black/40">READY TO GO</div><h3 className="mt-2 font-display text-2xl font-bold">{name.trim()||"My next adventure"}</h3><div className="mt-4 grid gap-3 sm:grid-cols-3"><div><span className="text-xs text-black/40">Dates</span><p className="font-bold">{formatDate(startDate)} — {formatDate(endDate||startDate)}</p></div><div><span className="text-xs text-black/40">Cities</span><p className="font-bold">{selectedCities.length} selected</p></div><div><span className="text-xs text-black/40">Budget</span><p className="font-bold">₹{(Number(budget)||0).toLocaleString("en-IN")}</p></div></div></div>}
 <div className="mt-8 flex flex-col-reverse gap-3 border-t border-black/5 pt-5 sm:flex-row sm:justify-between"><button type="button" onClick={()=>setStep(s=>Math.max(1,s-1))} className="btn-secondary w-full sm:w-auto" disabled={step===1}>Back</button><button type="button" onClick={next} className="btn-primary w-full sm:w-auto">{step===4?"Create trip":"Continue"}<ArrowRight size={16}/></button></div></div></div>;
}
