import { useState } from "react";
import { UserRound, Shield, Heart, Trash2, LogOut } from "lucide-react";
import { Toast } from "../components/ui";
import { useNavigate } from "react-router-dom";

export function Profile(){
 const [tab,setTab]=useState("Profile"); const [toast,setToast]=useState(""); const navigate=useNavigate();
 const logout=()=>{localStorage.removeItem("globetrotter_token"); navigate("/login",{replace:true});};
 const save=()=>{setToast("Profile updated successfully.");setTimeout(()=>setToast(""),2200)};
 return <div className="mx-auto max-w-4xl space-y-7"><div><div className="eyebrow">Account</div><h1 className="mt-2 font-display text-4xl font-extrabold">Profile & settings</h1></div><div className="panel overflow-hidden"><div className="flex gap-1 overflow-x-auto border-b border-black/5 p-2">{["Profile","Preferences","Saved Places","Privacy"].map(t=><button key={t} onClick={()=>setTab(t)} className={`rounded-xl px-4 py-2.5 text-sm font-semibold ${tab===t?"bg-mint/10 text-mint":"text-black/45"}`}>{t}</button>)}</div><div className="p-6 sm:p-8">{tab==="Profile"&&<div className="space-y-5"><div className="flex items-center gap-4"><div className="grid h-20 w-20 place-items-center rounded-full bg-[#d9e8e1] text-2xl font-bold text-mint">P</div><div><h2 className="font-display text-xl font-bold">Prem Mishra</h2><p className="text-sm text-black/45">prem@example.com</p></div></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="mb-2 block text-xs font-bold">Full name</label><input className="input" defaultValue="Prem Mishra"/></div><div><label className="mb-2 block text-xs font-bold">Email</label><input className="input" defaultValue="prem@example.com"/></div><div><label className="mb-2 block text-xs font-bold">Language</label><select className="input"><option>English</option><option>Hindi</option></select></div></div><div className="flex flex-wrap gap-3"><button onClick={save} className="btn-primary">Save changes</button><button onClick={logout} className="inline-flex items-center gap-2 rounded-xl border border-black/10 px-4 py-2.5 text-sm font-bold text-black/65 hover:bg-black/[.03]"><LogOut size={16}/> Log out</button></div></div>}{tab==="Preferences"&&<div><h2 className="font-display text-2xl font-bold">Travel preferences</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{["Budget friendly","Food experiences","Nature","Museums","Adventure","Nightlife"].map(x=><label key={x} className="flex items-center gap-3 rounded-2xl border border-black/5 p-4"><input type="checkbox" defaultChecked={x==="Food experiences"||x==="Nature"} className="accent-[#2F7D68]"/><span className="text-sm font-semibold">{x}</span></label>)}</div></div>}{tab==="Saved Places"&&<div><h2 className="font-display text-2xl font-bold">Saved destinations</h2><p className="mt-2 text-sm text-black/45">Paris, Tokyo, Kyoto, Bali</p></div>}{tab==="Privacy"&&<div><h2 className="font-display text-2xl font-bold">Privacy</h2><p className="mt-2 text-sm text-black/45">Control your data and account visibility.</p><button className="mt-6 inline-flex items-center gap-2 rounded-xl border border-red-200 px-4 py-2.5 text-sm font-bold text-red-600"><Trash2 size={16}/> Delete account</button></div>}</div></div>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>
}
