import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip, BarChart, Bar, XAxis, YAxis, CartesianGrid } from "recharts";
import { Link } from "react-router-dom";
import { ArrowLeft, TrendingDown, TrendingUp } from "lucide-react";

const pie=[{name:"Accommodation",value:30000},{name:"Transport",value:14500},{name:"Activities",value:11200},{name:"Food",value:14800},{name:"Other",value:4000}];
const bars=[{day:"Jun 10",spend:7800},{day:"Jun 11",spend:6900},{day:"Jun 12",spend:8200},{day:"Jun 13",spend:9100},{day:"Jun 14",spend:10600},{day:"Jun 15",spend:6500},{day:"Jun 16",spend:5700}];

export function Budget(){
 const total=74500,budget=80000;
 return <div className="space-y-7"><div><Link to="/trips/europe-adventure/builder" className="inline-flex items-center gap-2 text-sm font-semibold text-black/45"><ArrowLeft size={16}/> Back to builder</Link><div className="mt-5"><div className="eyebrow">Financial view</div><h1 className="mt-2 font-display text-4xl font-extrabold">Trip budget</h1><p className="mt-1 text-sm text-black/45">Europe Adventure · June 10 — 20, 2026</p></div></div>
 <div className="grid gap-4 md:grid-cols-3"><div className="panel p-5"><div className="text-xs font-bold text-black/40">TOTAL ESTIMATED</div><div className="mt-2 text-3xl font-extrabold">₹74,500</div><div className="mt-2 flex items-center gap-1 text-xs font-semibold text-mint"><TrendingDown size={14}/> 6.9% below budget</div></div><div className="panel p-5"><div className="text-xs font-bold text-black/40">BUDGET</div><div className="mt-2 text-3xl font-extrabold">₹80,000</div><div className="mt-2 text-xs text-black/40">Your planning target</div></div><div className="panel p-5"><div className="text-xs font-bold text-black/40">REMAINING</div><div className="mt-2 text-3xl font-extrabold text-mint">₹5,500</div><div className="mt-2 text-xs text-black/40">₹7,450 average / day</div></div></div>
 <div className="grid gap-5 lg:grid-cols-2"><div className="panel p-6"><h2 className="font-display text-xl font-bold">Where your money goes</h2><div className="mt-4 h-[300px]"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pie} dataKey="value" nameKey="name" innerRadius={72} outerRadius={105} paddingAngle={3}>{pie.map((_,i)=><Cell key={i} fill={["#2F7D68","#5E9D8A","#A6C9BD","#D4A85C","#B6B8B3"][i]}/>)}</Pie><Tooltip formatter={(v)=>`₹${Number(v).toLocaleString("en-IN")}`}/></PieChart></ResponsiveContainer></div><div className="grid grid-cols-2 gap-2 text-xs">{pie.map(x=><div key={x.name} className="flex justify-between rounded-lg bg-black/[.03] p-2"><span className="text-black/50">{x.name}</span><b>₹{x.value.toLocaleString("en-IN")}</b></div>)}</div></div>
 <div className="panel p-6"><h2 className="font-display text-xl font-bold">Daily spending</h2><div className="mt-5 h-[330px]"><ResponsiveContainer width="100%" height="100%"><BarChart data={bars}><CartesianGrid vertical={false} stroke="#00000010"/><XAxis dataKey="day" tick={{fontSize:11}}/><YAxis tick={{fontSize:11}}/><Tooltip formatter={(v)=>`₹${Number(v).toLocaleString("en-IN")}`}/><Bar dataKey="spend" radius={[7,7,0,0]} fill="#2F7D68"/></BarChart></ResponsiveContainer></div></div></div>
 <div className="grid gap-5 md:grid-cols-3"><div className="panel p-5"><div className="text-xs font-bold text-black/40">MOST EXPENSIVE DAY</div><div className="mt-2 font-display text-xl font-bold">June 14</div><div className="mt-1 text-sm text-black/45">₹10,600 planned</div></div><div className="panel p-5"><div className="text-xs font-bold text-black/40">CHEAPEST DAY</div><div className="mt-2 font-display text-xl font-bold">June 16</div><div className="mt-1 text-sm text-black/45">₹5,700 planned</div></div><div className="panel p-5"><div className="text-xs font-bold text-black/40">OPTIMIZATION</div><div className="mt-2 flex items-center gap-2 font-display text-xl font-bold"><TrendingUp size={19} className="text-mint"/> ₹4,500</div><div className="mt-1 text-sm text-black/45">Potential savings found</div></div></div>
 </div>
}
