import { useMemo, useState } from "react";
import { Plus, GripVertical, Clock3, Trash2, Wallet, ChevronRight, MapPin, Share2 } from "lucide-react";
import { Link } from "react-router-dom";
import { parisActivities } from "../data/mock";
import { Activity } from "../types";
import { Pill, Toast } from "../components/ui";

export function Builder() {
  const [activities,setActivities]=useState<Activity[]>([...parisActivities] as Activity[]);
  const [toast,setToast]=useState("");
  const [cities,setCities]=useState(["Paris","Amsterdam","Berlin"]);
  const budget=80000; const total=activities.reduce((s,a)=>s+a.cost,0)+70000;
  const remaining=budget-total; const avg=Math.round(total/10);
  const remove=(id:string)=>{setActivities(a=>a.filter(x=>x.id!==id));setToast("Activity removed.");setTimeout(()=>setToast(""),2200)};
  const add=()=>{const a:Activity={id:crypto.randomUUID(),name:"Seine River Cruise",category:"Sightseeing",time:"16:00",duration:"90 min",cost:2200,image:"https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=600&q=80"};setActivities(a=>[...a,a]);setToast("Seine River Cruise added.");setTimeout(()=>setToast(""),2200)};
  const move=(from:number,to:number)=>{if(to<0||to>=cities.length)return;const n=[...cities];const [x]=n.splice(from,1);n.splice(to,0,x);setCities(n);setToast("City order updated.");setTimeout(()=>setToast(""),1800)};
  const percent=Math.min(100,total/budget*100);
  return <div className="space-y-5">
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="eyebrow">Itinerary builder</div><h1 className="mt-2 font-display text-3xl font-extrabold">Europe Adventure</h1><p className="mt-1 text-sm text-black/45">10 Jun — 20 Jun · 10 days · {cities.length} cities</p></div><div className="flex gap-2"><button className="btn-secondary"><Share2 size={16}/> Share</button><Link to="/trips/europe-adventure/budget" className="btn-primary"><Wallet size={16}/> Budget</Link></div></div>
    <div className="grid gap-5 lg:grid-cols-[280px_minmax(0,1fr)_250px]">
      <aside className="panel h-fit p-4 lg:sticky lg:top-24"><div className="text-xs font-bold text-black/40">TRIP STOPS</div><div className="mt-4 space-y-2">{cities.map((c,i)=><div draggable onDragStart={e=>e.dataTransfer.setData("text/plain",String(i))} onDragOver={e=>e.preventDefault()} onDrop={e=>move(Number(e.dataTransfer.getData("text/plain")),i)} key={c} className="flex cursor-grab items-center gap-2 rounded-2xl border border-black/5 bg-black/[.015] p-3"><GripVertical size={16} className="text-black/25"/><div className="grid h-7 w-7 place-items-center rounded-lg bg-mint/10 text-xs font-bold text-mint">{i+1}</div><div className="flex-1"><b className="text-sm">{c}</b><div className="text-[11px] text-black/40">{i===0?"10 — 13 Jun":i===1?"14 — 16 Jun":"17 — 20 Jun"}</div></div><ChevronRight size={15} className="text-black/25"/></div>)}</div><button className="btn-secondary mt-3 w-full"><Plus size={15}/> Add stop</button><div className="mt-6 rounded-2xl bg-[#eef6f2] p-4"><div className="text-xs text-black/45">Live budget</div><div className="mt-1 text-lg font-extrabold">₹{total.toLocaleString("en-IN")}</div><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/10"><div className={`h-full ${remaining<0?"bg-red-500":"bg-mint"}`} style={{width:`${percent}%`}}/></div><div className={`mt-2 text-xs font-semibold ${remaining<0?"text-red-600":"text-mint"}`}>{remaining<0?`₹${Math.abs(remaining).toLocaleString("en-IN")} over budget`:`₹${remaining.toLocaleString("en-IN")} remaining`}</div></div></aside>
      <main className="space-y-5"><div className="panel p-5 sm:p-7"><div className="flex items-center justify-between"><div><Pill tone="green">DAY 1</Pill><h2 className="mt-3 font-display text-2xl font-bold">June 10 · Paris</h2></div><button onClick={add} className="btn-primary"><Plus size={16}/> Add activity</button></div><div className="mt-7 space-y-4">{activities.map(a=><div key={a.id} className="group flex gap-3 sm:gap-4"><div className="w-14 shrink-0 pt-4 text-right text-xs font-bold text-black/40">{a.time}</div><div className="relative min-w-0 flex-1 overflow-hidden rounded-2xl border border-black/5 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-card"><div className="flex flex-col sm:flex-row"><img src={a.image} className="h-28 w-full object-cover sm:h-24 sm:w-28"/><div className="min-w-0 flex-1 p-4"><div className="flex items-start justify-between gap-2"><div><Pill>{a.category}</Pill><h3 className="mt-2 font-bold">{a.name}</h3></div><button onClick={()=>remove(a.id)} className="rounded-lg p-1.5 text-black/25 opacity-100 hover:bg-red-50 hover:text-red-500"><Trash2 size={16}/></button></div><div className="mt-2 flex flex-wrap gap-3 text-xs text-black/45"><span className="flex items-center gap-1"><Clock3 size={13}/>{a.duration}</span><span className="font-bold text-ink">₹{a.cost.toLocaleString("en-IN")}</span></div></div></div></div></div>)}</div></div><div className="rounded-2xl border border-dashed border-black/10 p-5 text-center"><button onClick={add} className="text-sm font-bold text-mint"><Plus size={16} className="mr-1 inline"/> Add another activity</button></div><div className="panel p-5"><div className="flex items-center gap-2"><MapPin size={18} className="text-mint"/><b>Next stop</b></div><div className="mt-3 flex items-center justify-between"><div><h3 className="font-display text-xl font-bold">Amsterdam</h3><p className="text-sm text-black/45">14 — 16 Jun</p></div><button className="btn-secondary">Plan stop <ChevronRight size={15}/></button></div></div></main>
      <aside className="space-y-4"><div className="panel p-5 lg:sticky lg:top-24"><div className="flex items-center justify-between"><span className="text-xs font-bold text-black/40">TRIP BUDGET</span><Link className="text-xs font-bold text-mint" to="/trips/europe-adventure/budget">Details</Link></div><div className="mt-4 text-3xl font-extrabold">₹{total.toLocaleString("en-IN")}</div><div className="mt-1 text-xs text-black/40">of ₹{budget.toLocaleString("en-IN")}</div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span className="text-black/50">Estimated</span><b>₹{total.toLocaleString("en-IN")}</b></div><div className="flex justify-between"><span className="text-black/50">Remaining</span><b className={remaining<0?"text-red-600":"text-mint"}>₹{remaining.toLocaleString("en-IN")}</b></div><div className="flex justify-between"><span className="text-black/50">Avg / day</span><b>₹{avg.toLocaleString("en-IN")}</b></div></div>{remaining<0&&<div className="mt-5 rounded-xl bg-red-50 p-3 text-xs font-semibold text-red-600">⚠ Your trip is over budget. Consider lowering accommodation or replacing an expensive activity.</div>}</div></aside>
    </div>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>
}
