import { useMemo, useState } from "react";
import { Search, SlidersHorizontal, Plus, Check } from "lucide-react";
import { cities } from "../data/mock";
import { Toast } from "../components/ui";

export function Cities(){
 const [q,setQ]=useState(""); const [added,setAdded]=useState<string[]>([]); const [toast,setToast]=useState("");
 const filtered=useMemo(()=>cities.filter(c=>`${c.name} ${c.country}`.toLowerCase().includes(q.toLowerCase())),[q]);
 const add=(name:string)=>{setAdded(a=>[...new Set([...a,name])]);setToast(`${name} added to your trip.`);setTimeout(()=>setToast(""),2000)};
 return <div className="space-y-7"><div><div className="eyebrow">Discover</div><h1 className="mt-2 font-display text-4xl font-extrabold">Where do you want to go?</h1><p className="mt-2 text-sm text-black/45">Find destinations by vibe, cost, and popularity.</p></div><div className="flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 text-black/35" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} className="input pl-10" placeholder="Search cities..."/></div><button className="btn-secondary"><SlidersHorizontal size={17}/> <span className="hidden sm:inline">Filters</span></button></div><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map(c=><div key={c.id} className="panel group overflow-hidden"><div className="relative h-52"><img src={c.image} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute bottom-3 left-3 rounded-full bg-white/90 px-3 py-1 text-xs font-bold backdrop-blur">{c.costIndex} · {c.popularity}% popular</div></div><div className="p-5"><h2 className="font-display text-xl font-bold">{c.name}</h2><p className="text-sm text-black/45">{c.country} · {c.region}</p><button onClick={()=>add(c.name)} className={`mt-5 w-full rounded-xl px-4 py-3 text-sm font-bold ${added.includes(c.name)?"bg-mint/10 text-mint":"bg-ink text-white hover:bg-black"}`}>{added.includes(c.name)?<><Check size={16} className="mr-1 inline"/> Added</>:<><Plus size={16} className="mr-1 inline"/> Add to trip</>}</button></div></div>)}</div>{toast&&<Toast message={toast} onClose={()=>setToast("")}/>}</div>
}
