import { Link, useParams } from "react-router-dom";
import { ArrowLeft, Share2 } from "lucide-react";
import { trips } from "../data/mock";
import { Pill } from "../components/ui";

export function Itinerary(){
 const trip=trips[0];
 return <div className="mx-auto max-w-5xl space-y-7"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-black/45"><ArrowLeft size={16}/> Back</Link><div className="relative overflow-hidden rounded-[30px]"><img src={trip.cover} className="h-[360px] w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 to-transparent"/><div className="absolute bottom-7 left-6 right-6 text-white sm:left-9"><Pill tone="green">10 days · 3 cities</Pill><h1 className="mt-3 font-display text-4xl font-extrabold">Europe Adventure</h1><p className="mt-2 text-white/75">Paris → Amsterdam → Berlin · June 10–20, 2026</p></div></div><div className="grid gap-4 sm:grid-cols-3"><div className="panel p-5"><span className="text-xs text-black/40">Duration</span><b className="mt-1 block text-xl">10 days</b></div><div className="panel p-5"><span className="text-xs text-black/40">Cities</span><b className="mt-1 block text-xl">3</b></div><div className="panel p-5"><span className="text-xs text-black/40">Estimated</span><b className="mt-1 block text-xl">₹74,500</b></div></div><div className="flex items-center justify-between"><h2 className="font-display text-2xl font-bold">Trip overview</h2><button className="btn-primary"><Share2 size={16}/> Share trip</button></div><div className="space-y-5">{[["DAY 1","June 10","Paris"],["DAY 2","June 11","Paris"],["DAY 5","June 14","Amsterdam"],["DAY 8","June 17","Berlin"]].map((d,i)=><div className="panel p-5 sm:p-6" key={i}><div className="flex items-center gap-3"><Pill tone="green">{d[0]}</Pill><span className="text-sm font-semibold text-black/45">{d[1]}</span></div><h3 className="mt-3 font-display text-xl font-bold">{d[2]}</h3><p className="mt-1 text-sm text-black/45">Your planned activities, meals, and travel blocks for the day.</p></div>)}</div></div>
}
